layout_spectrum: 0.9587814
color:
  saturation: 0.8870968
  brandStrength: 0.4223249
  lightness: 0.7033508
  rhythmicContrast: 0.6021506
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.2903226
name: Göttlicher
navigation:
  - id: 2414155a-96ae-43bb-a58c-935e63062ca2
    url: 2016-07-19-alzheimer-punt-de-focus.html
    name: Video
    type: content
  - id: d2bfb90e-0191-4bf6-9dea-b45930a8e67d
    url: 2016-07-19-laufbursche-tv-visafreie-einreise.html
    name: 'Laufbursche TV: Visafreie Einreise'
    type: content
