typography_spectrum: 0.3136201
color:
  saturation: 0.8870968
  brandStrength: 0.4223249
  rhythmicContrast: 0.6021506
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.7033508
layout_spectrum: 1
name: Göttlicher
navigation:
  - name: Photography
    url: 'http://www.goettlicher-photo.com'
    type: external
  - name: Multimedia
    url: 'http://puntdefocus.com/en/'
    type: external
  - name: Satiremagazin
    url: 'http://lauf-bursche.com'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
